# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

for_window [class=".*"] border pixel 2
gaps inner 12
gaps outer 0
smart_gaps on

smart_borders on
smart_borders no_gaps
border_radius 4

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:Ubuntu Mono Regular 16

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# The combination of xss-lock, nm-applet and pactl is a popular choice, so
# they are included here as an example. Modify as you see fit.

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock-fancy-multimonitor -b=10x10

# Autostart 
exec --no-startup-id autorandr -c
exec --no-startup-id nm-applet
exec --no-startup-id /home/magne/bin/wallpaper.sh
exec --no-startup-id blueberry-tray
exec --no-startup-id flameshot
exec --no-startup-id redshift-gtk
exec --no-startup-id twmnd
# exec --no-startup-id picom -b --experimental-backend
exec_always --no-startup-id autotiling
exec_always --no-startup-id $HOME/.config/polybar/launch.sh

# Use pactl to adjust volume in PulseAudio.
set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle
bindsym XF86AudioPlay exec --no-startup-id playerctl -a play-pause
bindsym XF86AudioStop exec --no-startup-id playerctl -a stop
bindsym XF86AudioNext exec --no-startup-id playerctl -a next
bindsym XF86AudioPrev exec --no-startup-id playerctl -a previous
bindsym XF86MonBrightnessUp exec --no-startup-id xbacklight -inc 10
bindsym XF86MonBrightnessDown exec --no-startup-id xbacklight -dec 10
bindsym Print exec --no-startup-id flameshot gui
bindsym $mod+Print exec --no-startup-id flameshot screen -c

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec alacritty

# kill focused window
bindsym $mod+Shift+q kill

# lock screen
bindsym $mod+Ctrl+l exec "loginctl lock-session"

# start dmenu (a program launcher)
bindsym $mod+d exec "rofi -show run"

# Unicode Picker
bindsym $mod+u exec "unipicker --copy --command 'rofi -dmenu'"
bindsym $mod+e exec "rofi -show emoji -modi emoji"

# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# split in horizontal orientation
# bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+a layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
# bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

# resize window (you can also use the mouse for that)
mode "resize" {
    # These bindings trigger as soon as you enter the resize mode

    # Pressing left will shrink the window’s width.
    # Pressing right will grow the window’s width.
    # Pressing up will shrink the window’s height.
    # Pressing down will grow the window’s height.
    bindsym h resize shrink width 5 px or 5 ppt
    bindsym j resize shrink height 5 px or 5 ppt
    bindsym k resize grow height 5 px or 5 ppt
    bindsym l resize grow width 5 px or 5 ppt

    # same bindings, but for the arrow keys
    bindsym Left resize shrink width 5 px or 5 ppt
    bindsym Down resize grow height 5 px or 5 ppt
    bindsym Up resize shrink height 5 px or 5 ppt
    bindsym Right resize grow width 5 px or 5 ppt

    # back to normal: Enter or Escape or $mod+r
    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym $mod+r mode "default"
}

mode "move" {
    # move focused window
    bindsym $mod+h move left
    bindsym $mod+j move down
    bindsym $mod+k move up
    bindsym $mod+l move right

    # move focused container to workspace
    bindsym $mod+1 move container to workspace number $ws1
    bindsym $mod+2 move container to workspace number $ws2
    bindsym $mod+3 move container to workspace number $ws3
    bindsym $mod+4 move container to workspace number $ws4
    bindsym $mod+5 move container to workspace number $ws5
    bindsym $mod+6 move container to workspace number $ws6
    bindsym $mod+7 move container to workspace number $ws7
    bindsym $mod+8 move container to workspace number $ws8
    bindsym $mod+9 move container to workspace number $ws9
    bindsym $mod+0 move container to workspace number $ws10

    bindsym $mod+Shift+h move workspace to output left
    bindsym $mod+Shift+l move workspace to output right

    # back to normal: Enter or Escape or $mod+m
    bindsym Return mode "default"
    bindsym Escape mode "default"
    bindsym $mod+m mode "default"
}

mode "workspace" {
    bindsym 1 workspace "1" mode "default"
    bindsym $mod+1 move container to workspace "1" mode "default"
    bindsym 2 workspace "2" mode "default"
    bindsym $mod+2 move container to workspace "2" mode "default"
    bindsym 3 workspace "3" mode "default"
    bindsym $mod+3 move container to workspace "3" mode "default"
    bindsym 4 workspace "4" mode "default"
    bindsym $mod+4 move container to workspace "4" mode "default"
    bindsym 5 workspace "5" mode "default"
    bindsym $mod+5 move container to workspace "5" mode "default"
    bindsym 6 workspace "6" mode "default"
    bindsym $mod+6 move container to workspace "6" mode "default"
    bindsym 7 workspace "7" mode "default"
    bindsym $mod+7 move container to workspace "7" mode "default"
    bindsym 8 workspace "8" mode "default"
    bindsym $mod+8 move container to workspace "8" mode "default"
    bindsym 9 workspace "9" mode "default"
    bindsym $mod+9 move container to workspace "9" mode "default"
    bindsym 0 workspace "10" mode "default"
    bindsym $mod+0 move container to workspace "10" mode "default"
    bindsym q workspace "q" mode "default"
    bindsym $mod+q move container to workspace "q" mode "default"
    bindsym w workspace "w" mode "default"
    bindsym $mod+w move container to workspace "w" mode "default"
    bindsym e workspace "e" mode "default"
    bindsym $mod+e move container to workspace "e" mode "default"
    bindsym r workspace "r" mode "default"
    bindsym $mod+r move container to workspace "r" mode "default"
    bindsym $mod+g mode "default"
}

bindsym $mod+r mode "resize"
bindsym $mod+m mode "move"
bindsym $mod+g mode "workspace"

workspace "q" output DP-2
workspace "w" output DP-2
workspace "e" output DP-4
workspace "r" output DP-4

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
# bar {
#     status_command i3status

#     font pango:Ubuntu Mono Regular 16

#     tray_output primary
#     colors {
#         background #2A2A2A
#         statusline #DDDDDD
#     }
# }
